#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <sys/time.h>
#include <fcntl.h>
#include <fstream>
#include <termios.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netinet/tcp.h>
#include <getopt.h>
#include <pthread.h>
#include <string>
#include <string.h>
#include "stdio.h"
#include <cstdio>
#include <cmath>
#include <cstdarg>
#include <cstdlib>
#include <signal.h>
#include <time.h>
#include <queue>
