#include <arpa/inet.h>
#include <algorithm>
#include <cstdio>
#include <cmath>
#include <cstdarg>
#include <cstdlib>
#include <deque>
#include <fcntl.h>
#include <fstream>
#include <functional>
#include <float.h>
#include <getopt.h>
#include <iosfwd>
#include <iostream>
#include <list>
#include <limits.h>
#include <memory>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <pthread.h>
#include <queue>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <sys/time.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <string>
#include <string.h>
#include <sstream>
#include "stdio.h"
#include <signal.h>
#include <time.h>
#include <termios.h>
#include <utility>
#include <unistd.h>
#include <vector>

using namespace std;
using std::string;

